#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

// Define the application
$application = new Application('mono', '1.0.0');

// Define the "generate:code" command
$application
    ->register('generate:view')
    ->setDescription('Generate a view file')
    ->addArgument('name', InputArgument::REQUIRED, 'The name of the code file')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $name = $input->getArgument('name');
        $filename = __DIR__."/{$name}.php";
        if (file_exists($filename)) {
            throw new RuntimeException("File {$name}.php already exists");
        }
        file_put_contents($filename, "<?php\n\n// Your code here\n");
        $output->writeln("Code file {$name}.php generated");
    });

// Run the application
$application->run();
