<?php 
// Require autoload.php auto-generated by composer
require_once dirname(__DIR__, 1) . '/vendor/autoload.php';

use MonoLib\Lib\Config;
use MonoLib\Lib\App\App;

/*
    ------------------------------------------------------------------------------------------
                            Check if project is under maintenence
    ------------------------------------------------------------------------------------------
    Check if project is under maintenence through config at root of project.
    If so, require the maintence view, then stop everything else, if not done
    can cause errors.
*/
$isMaintenence = Config::get('UNDER_MAINTENENCE') == 'true';
if($isMaintenence) {
    require '../resources/views/maintenence.php';
    return;
}

/*
    ------------------------------------------------------------------------------------------
                                    Routing is very cool
    ------------------------------------------------------------------------------------------
    Includes routes/web.php from the root of the project which (hopefully) includes
    every route in your project. Routing is safer than just using the file system to do your job
    for you, as "file-system routing" exposes the project structure to vistors.
*/

include dirname(__DIR__, 1) . '/routes/web.php';

/*
    ------------------------------------------------------------------------------------------
                                     Initialize our app
    ------------------------------------------------------------------------------------------
    Initializes the logger and starts a session.
*/

App::init();